print("Please enter your name")
name = input()
print("Please enter your age")
age = input()
age = int(age)
print("Please enter your salary")
salary = input()
salary = float(salary)
print("the below are your details")
print("name:", name)
print("age:", age)
print("salary:", salary)
