print("Equal to")
print(10 == 5)
print("Not Equal to")
print(10 != 5)
print("Greater than")
print(10 > 5)
print("Less than")
print(10 < 5)
print("Greater than or equal")
print(10 >= 5)
print("Less than or equal")
print(10 <= 5)